export const CONDITIONS = {
  xs: '@media screen and (max-width: 639px)',
  sm: '@media screen and (min-width: 640px) and (max-width: 767px)',
  md: '@media screen and (min-width: 768px) and (max-width: 1023px)',
  lg: '@media screen and (min-width: 1024px) and (max-width: 1279px)',
  xl: '@media screen and (min-width: 1280px) and (max-width: 1535px)',
  '2xl': '@media screen and (min-width: 1536px)',
  downXs: '@media screen and (max-width: 639px)',
  downSm: '@media screen and (max-width: 767px)',
  downMd: '@media screen and (max-width: 1023px)',
  downLg: '@media screen and (max-width: 1279px)',
  downXl: '@media screen and (max-width: 1535px)',
  upSm: '@media screen and (min-width: 640px)',
  upMd: '@media screen and (min-width: 768px)',
  upLg: '@media screen and (min-width: 1024px)',
  upxl: '@media screen and (min-width: 1280px)',
  up2xl: '@media screen and (min-width: 1536px)',
};
